[package]
name = "formana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "formana_program"

[dependencies]
borsh = "1.5.1"
solana-program = "2.0.1"
thiserror = "1.0.61"
